version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "1186:1186"
    depends_on:
      - Auth
      - Classrooms
      - event-bus
    
  
  auth:
    build:
      context: ./auth
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - CLASSROOMS_SERVICE_URL=http://classrooms:5000
      - EVENT_BUS_SERVICE_URL=http://event-bus:5000
    depends_on:
      - mongo

  volumes:
    mongo-data
  